version: '3.4'

services:
  letease.api:
    image: ${DOCKER_REGISTRY-}leteaseapi
    build:
      context: .
      dockerfile: LetEase.API/Dockerfile
    network_mode: host
      # - ConnectionStrings__DefaultConnection=Server=OXLEYNETWEB01;Database=LetEase;User=sa;Password=Joyce1975;TrustServerCertificate=True